### PR TITLE
Reoarganize files, add tests

### PR DESCRIPTION
**Pull request by jotak**
Use a more common directory structure:
- main package moved to `cmd/`
- other (api) packages moved to `pkg/`

Some small simplifications here and there

Tests:
- Use testing lib `testify`
- Create a mock for Informers
- Test enricher algo

### CODE REVIEW

**Comment by jotak** [comment]
cc @OlivierCazade @mariomac could you do a review?

I hope with a cleaner directory structure and some tests introduced it can be a better starting point for the next changes / consuming goflow as a lib.

More tests will be necessary, but it's a start

**Comment by OlivierCazade** [comment]
Hello,
I cannot find the cmd/ directory, did you push it ?

**Review by mariomac — APPROVED** [review]

**Comment by OlivierCazade** [comment]
Just a suggestion, I would have put the mock Informer under a separated test/ directory (same level than pkg and cmd).

I think this would have two benefits :
- Having a clearer distinction between test code and application code.
- Prevent the Mock from beeing exported by godoc

**Comment by mariomac** [comment]
Another option to avoid exporting the mock is to rename the package path to `pkg/internal/mock`.

https://dave.cheney.net/2019/10/06/use-internal-packages-to-reduce-your-public-api-surface

**Comment by jotak** [comment]
@OlivierCazade @mariomac added a simple makefile, and moved the mock to `pkg/internal`

**Review by OlivierCazade — APPROVED** [review]

**Pull request merged**
